### PR TITLE
Minor changes in Assets.js

### PR DESCRIPTION
**Pull request by jkokh**

### CODE REVIEW

**Review by EGreg — COMMENTED** [review]
1. Did you test it?

2. You need Q.addScript to add the v2 script in case it wasn't added, in both private functions.

3. Have a config in Assets plugin called "Assets"/"stripe"/"preloadAPI" which defaults to true, and controls the addScript in the responseExtras hook.

**Review by EGreg — CHANGES_REQUESTED** [review]
1. Did you test it?

2. You need Q.addScript to add the v2 script in case it wasn't added, in both private functions.

3. Have a config in Assets plugin called "Assets"/"stripe"/"preloadAPI" which defaults to true, and controls the addScript in the responseExtras hook.

**Comment by EGreg** [comment]
Hey please do 1,2,3

**Comment by jkokh** [comment]
For step 2:
Can't wrap Stripe.applePay.buildSession into Q.AddScript because of the js error:
> You attempt to create ApplePaySession outside of a gesture handler.

https://developer.apple.com/documentation/applepayjs/applepaysession/2320659-applepaysession
I guess in this case Stripe object should be always preloaded.

There are no errors if used wrapped _paymentRequestStripe (it is a second private function that you mentioned).

**Review by EGreg — APPROVED** [review]

**Pull request merged**
