### PR TITLE
Modified .hgignore

### PR DESCRIPTION
**Pull request by AndreyTepaykin**
Please look description: https://drive.google.com/file/d/1a9HzNIzT4rnttaycnYvNW7GHzc7LPwwp/view?usp=sharing

### CODE REVIEW

**Comment by EGreg** [comment]
You didn't understand @AndreyTepaykin , it's the opposite.

Google "regexp what does ?! mean" it is negative lookahead, which means we ignore all files EXCEPT the files `files/MyApp/uploads/Users/(?!.dir)`
Why don't we ignore them? So we can CREATE THIS DIRECTORY when we add app to repo. And then everyone who checks out a clone of this repo will have the directory.
Otherwise our installer would have to create these directories, which isn't bad, but .hgignore was done this wayinstead.

**Comment by AndreyTepaykin** [comment]
Did you see my video explanation?

**Comment by AndreyTepaykin** [comment]
I return back rules for files/MyApp/uploads/Users and files/MyApp/uploads/Streams
Please review again.

**Review by EGreg — CHANGES_REQUESTED** [review]
So why do you do this change, also?

Now it will ignore the entire ^web/Q folder and not even create it, in cloned repos.

It should probably allow ^web/Q/.dir for same reason, but ignore those directories because installer will create them.

So - nothing to change in hgignore, this pull request can be closed

**Pull request closed without merging**
