### PR TITLE
Improved tool Users/list. Make it possible to fetch not only array but also object.

### PR DESCRIPTION
**Pull request by AndreyTepaykin**

### CODE REVIEW

**Review by EGreg — APPROVED** [review]

**Review by EGreg — CHANGES_REQUESTED** [review]
I don't see where you are using length anymore. It seems to me that the old code was correct... it only loads what was needed to be loaded. Now you load all of them. Well, okay, I guess if we have lazyload, that is okay maybe. But if you don't have lazyload? I think you should be calling loadMore until you reach bottom of tool, instead.

**Comment by AndreyTepaykin** [comment]
Fixed. Please look last commit

**Review by EGreg — CHANGES_REQUESTED** [review]
I am curious, what is the point of iterating over all the elements like this, if you can just iterate fro this.loaded to length? Seems that is what it was before.

**Comment by AndreyTepaykin** [comment]
This way we can iterate not only array, but also objects like {"0": "userId", ...}. It will increase tool stability.
Because I got this situation in Yang communities.

**Comment by EGreg** [comment]
> This way we can iterate not only array, but also objects like {"0": "userId", ...}. It will increase tool stability.
> Because I got this situation in Yang communities.

In that case, just pass `numeric: true` option to `Q.each()` and I will accept

**Comment by AndreyTepaykin** [comment]
Done. Look please last commit.

**Review by EGreg — APPROVED** [review]

**Pull request merged**
